<?xml version="1.0"?>

<package format="3">
  <name>sawit_autonomy</name>
  <version>0.0.1</version>

  <description>
    RGB-D SLAM and autonomous oil-palm navigation
    experiments using ROS 2 and PX4 SITL.
  </description>

  <maintainer email="rafifdarkblood4869@gmail.com">
    Rafif Fernanda Wibowo
  </maintainer>

  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>sensor_msgs_py</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>nav_msgs</exec_depend>
  <exec_depend>visualization_msgs</exec_depend>

  <exec_depend>tf2_ros</exec_depend>

  <exec_depend>rtabmap_launch</exec_depend>
  <exec_depend>rtabmap_odom</exec_depend>
  <exec_depend>rtabmap_slam</exec_depend>
  <exec_depend>rtabmap_sync</exec_depend>
  <exec_depend>rtabmap_util</exec_depend>

  <exec_depend>px4_msgs</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>